export const userRoles = {
  master: 'Master Admin',
  chapter: 'Chapter Admin',
  member: 'Brewery Admin',
  staff: 'Brewery Staff',
  agent: 'Agent',
  enthusiast: 'Enthusiast',
};

export const userPermissions = [{
  value: 'forum',
  label: 'Access Forum',
  roles: [
    // 'member',
    // 'staff',
  ],
}, {
  value: 'blog',
  label: 'Manage Blog',
  roles: [
    // 'agent',
  ],
}, {
  value: 'events',
  label: 'Manage Events',
  roles: [
    'member',
    // 'agent',
  ],
}, {
  value: 'submit_events',
  label: 'Submit Festival Events',
  roles: [
    'agent',
  ],
}, {
  value: 'events_free',
  label: 'Waive Festival Event Submission Fee',
  roles: [
    'agent',
  ],
}, {
  value: 'sponsor',
  label: 'Assign to Festival Sponsor',
  roles: [
    'agent',
  ],
}, {
  value: 'subscription',
  label: 'Cancel Subscription & Manage Payment Sources',
  roles: [
    // 'member',
  ],
}, {
  value: 'voting',
  label: 'Vote in Polls',
  roles: [
    // 'member',
  ],
}];

export const sfbwCategories = [
  {
    value: 'beer_dinner',
    label: 'Beer Dinner',
    icon: 'restaurant',
  },
  {
    value: 'food_pairings',
    label: 'Food Pairings',
    icon: 'restaurant_menu',
  },
  {
    value: 'special_release',
    label: 'Special Release',
    icon: 'local_drink',
  },
  {
    value: 'style_showcase',
    label: 'Style Showcase',
    icon: 'star',
  },
  {
    value: 'festival_celebration',
    label: 'Festival / Celebration',
    icon: 'cake',
  },
  {
    value: 'tap_takeover',
    label: 'Tap Takeover',
    icon: 'new_releases',
  },
  {
    value: 'meet_the_brewers',
    label: 'Meet the Brewers',
    icon: 'face',
  },
  {
    value: 'at_brewery',
    label: 'At Brewery',
    icon: 'store_mall_directory',
  },
  {
    value: 'tour',
    label: 'Tour',
    icon: 'directions',
  },
  {
    value: 'education',
    label: 'Education',
    icon: 'school',
  },
  {
    value: 'fundraiser',
    label: 'Fundraiser',
    icon: 'local_atm',
  },
  {
    value: 'other_unique',
    label: 'Other Unique',
    icon: 'category',
  },
  {
    value: 'outdoor_activity',
    label: 'Outdoor Activity',
    icon: 'wb_sunny',
  },
];

export const categoryIcons = {
  'Rare Beers': 'local_drink',
  'Meet the Brewer': 'face',
  'Charity & Community Events': 'local_florist',
  'Beer Festivals': 'assistant',
  Other: 'local_drink',
  'Activities & Sports': 'golf_course',
  'Food Pairings': 'restaurant',
  'Special Casks': 'local_bar',
  'Beer Releases': 'local_drink',
  'Beer Promotions': 'flag',
  'Educational Events': 'school',
  'Trivia & Games': 'videogame_asset',
  'Arts & Crafts': 'brush',
  Anniversaries: 'cake',
  'Live Music': 'music_note',
  'Member Only': 'assistant_photo',
};

export const beerTypes = [
  'Pale Ales',
  'Dark Lagers',
  'Brown Ales',
  'IPAs',
  'Wheat Beers',
  'Stouts',
  'Porters',
  'Bocks',
  'Hybrid Beers',
  'Belgian Styles',
  'Strong Ales',
  'Scottish-Style Ales',
  'Wild/Sour Ales',
  'Pilsners and Pale Lagers',
  'Specialty Beers',
];

export const categories = [
  'Beer Festivals',
  'Food Pairings',
  'Anniversaries',
  'Arts & Crafts',
  'Beer Promotions',
  'Charity & Community Events',
  'Educational Events',
  'Beer Releases',
  'Activities & Sports',
  'Trivia & Games',
  'Meet the Brewer',
  'Live Music',
  'Rare Beers',
  'Special Casks',
];

export const locationStages = [{
  value: 'operating',
  label: 'Operating',
  icon: 'store',
  color: '#388E3C',
  badgeColor: 'rgba(56, 142, 60, 0.1)',
}, {
  value: 'closed',
  label: 'Closed',
  icon: 'remove_circle_outline',
  color: '#D32F2F',
  badgeColor: 'rgba(211, 47, 47, 0.1)',
}, {
  value: 'in-planning',
  label: 'In Planning',
  icon: 'schedule',
  color: '#FFA000',
  badgeColor: 'rgba(255, 160, 0, 0.1)',
}];

export const locationOptions = [
  { value: 'restaurant', label: 'Restaurant' },
  { value: 'taproom', label: 'Taproom' },
  { value: 'retail-bottle', label: 'Retail/Bottle Shop' },
  { value: 'growlers', label: 'Growlers' },
  { value: 'crowlers', label: 'Crowlers' },
  { value: 'select-food', label: 'Select Food Options' },
  { value: 'food-trucks', label: 'Food Trucks' },
  { value: 'brewery-tours', label: 'Brewery Tours' },
  { value: 'entertainment', label: 'Entertainment' },
  { value: 'outside-seating', label: 'Outside Seating' },
  { value: 'kid-friendly', label: 'Kid Friendly' },
  { value: 'pet-friendly', label: 'Pet Friendly' },
  { value: 'wi-fi', label: 'Wi-Fi' },
  { value: 'private', label: 'Private/Not Open to Public' },
];

// derived from the California Department of Alcoholic Beverage Control
// https://www.abc.ca.gov/permits/licensetypes.html
export const licenseTypes = [
  { value: '01', label: 'Beer Manufacturer' },
  { value: '02', label: 'Winegrower' },
  { value: '03', label: 'Brandy Manufacturer' },
  { value: '04', label: 'Distilled Spirits Manufacturer' },
  { value: '05', label: 'Distilled Spirits Manufacturer\'s Agent' },
  { value: '06', label: 'Still' },
  { value: '07', label: 'Rectifier' },
  { value: '08', label: 'Wine Rectifier' },
  { value: '09', label: 'Beer and Wine Importer' },
  { value: '10', label: 'Beer and Wine Importer\'s General' },
  { value: '11', label: 'Brandy Importer' },
  { value: '12', label: 'Distilled Spirits Importer' },
  { value: '13', label: 'Distilled Spirits Importer\'s General' },
  { value: '14', label: 'Public Warehouse' },
  { value: '15', label: 'Customs Broker' },
  { value: '16', label: 'Wine Broker' },
  { value: '17', label: 'Beer and Wine Wholesaler' },
  { value: '18', label: 'Distilled Spirits Wholesaler' },
  { value: '19', label: 'Industrial Alcohol Dealer' },
  { value: '20', label: 'Off-Sale Beer and Wine' },
  { value: '21', label: 'Off-Sale General' },
  { value: '22', label: 'Wine Blender' },
  { value: '23', label: 'Small Beer Manufacturer' },
  { value: '24', label: 'Distilled Spirits Rectifier\'s General' },
  { value: '25', label: 'California Winegrowers Agent' },
  { value: '26', label: 'Out-of-State Beer Manufacturer\'s Certificate' },
  { value: '27', label: 'California Winegrowers Agent' },
  { value: '28', label: 'Out-of-State Distilled Spirits Shipper\'s Certificate' },
  { value: '29', label: 'Winegrape Grower\'s Certificate' },
  { value: '30', label: 'Temporary Retail Permit' },
  { value: '31', label: 'Special Daily License' },
  { value: '32', label: 'Daily Beer' },
  { value: '33', label: 'Daily Wine' },
  { value: '34', label: 'Daily Beer and Wine' },
  { value: '37', label: 'Daily On-Sale General' },
  { value: '40', label: 'On-Sale Beer' },
  { value: '41', label: 'On-Sale Beer and Wine for Bona Fide Public Eating Place' },
  { value: '42', label: 'On-Sale Beer and Wine for Public Premises' },
  { value: '43', label: 'On-Sale Beer and Wine for Train' },
  { value: '44', label: 'On-Sale Beer for Fishing Party Boat' },
  { value: '45', label: 'On-Sale Beer and Wine for Boat' },
  { value: '46', label: 'On-Sale Beer and Wine for Airplane' },
  { value: '47', label: 'On-Sale General for Bona Fide Public Eating Place' },
  { value: '48', label: 'On-Sale General for Public Premises' },
  { value: '49', label: 'On-Sale General for Seasonal Business' },
  { value: '50', label: 'On-Sale General for Club' },
  { value: '51', label: 'Club' },
  { value: '52', label: 'Veterans\' Club' },
  { value: '53', label: 'On-Sale General for Train' },
  { value: '54', label: 'On-Sale General for Boat' },
  { value: '55', label: 'On-Sale General for Airplane' },
  { value: '56', label: 'On-Sale General for Vessel of more than 1,000 tons burden' },
  { value: '57', label: 'Special On-Sale General' },
  { value: '58', label: 'Caterer\'s Permit' },
  { value: '59', label: 'On-Sale Beer and Wine for Seasonal Business' },
  { value: '60', label: 'On-Sale Beer for Seasonal Business' },
  { value: '61', label: 'On-Sale Beer for Public Premises' },
  { value: '62', label: 'On-Sale Beer General Bona Fide Public Eating Place Intermittent Dockside Vessel' }, // eslint-disable-line
  { value: '63', label: 'On-Sale Beer and Wine for Hospital' },
  { value: '64', label: 'Special On-Sale General Theater' },
  { value: '65', label: 'Special On-Sale Beer and Wine, Symphony' },
  { value: '66', label: 'Controlled Access Cabinet Permit' },
  { value: '67', label: 'Bed and Breakfast Inn' },
  { value: '68', label: 'Portable Bar' },
  { value: '69', label: 'Special On-Sale Beer & Wine Theater' },
  { value: '70', label: 'On-Sale General Restrictive Service' },
  { value: '71', label: 'Special On-Sale General License' },
  { value: '74', label: 'Craft Distiller' },
  { value: '75', label: 'On-Sale General Brew-Pub' },
  { value: '76', label: 'On-Sale General Maritime Museum Association' },
  { value: '77', label: 'Event Permit' },
  { value: '78', label: 'On-Sale General Wine, Food and Art Cultural Museum' },
  { value: '79', label: 'Certified Farmers\' Market Sales Permit' },
  { value: '80', label: 'Special On-Sale General Bed and Breakfast Inn' },
  { value: '81', label: 'Wine Sales Event Permit' },
  { value: '82', label: 'Direct Shippers Permit' },
  { value: '83', label: 'On-Sale General Caterer\'s License' },
  { value: '84', label: 'Certified Farmers\' Market Beer Sales Permit' },
  { value: '85', label: 'Limited Off-Sale Retail Wine License' },
  { value: '86', label: 'Instructional Tasting License' },
];

export const fontAwesomeIcons = [
  'ad',
  'address-book',
  'address-card',
  'adjust',
  'air-freshener',
  'align-center',
  'align-justify',
  'align-left',
  'align-right',
  'allergies',
  'ambulance',
  'american-sign-language-interpreting',
  'anchor',
  'angle-double-down',
  'angle-double-left',
  'angle-double-right',
  'angle-double-up',
  'angle-down',
  'angle-left',
  'angle-right',
  'angle-up',
  'angry',
  'ankh',
  'apple-alt',
  'archive',
  'archway',
  'arrow-alt-circle-down',
  'arrow-alt-circle-left',
  'arrow-alt-circle-right',
  'arrow-alt-circle-up',
  'arrow-circle-down',
  'arrow-circle-left',
  'arrow-circle-right',
  'arrow-circle-up',
  'arrow-down',
  'arrow-left',
  'arrow-right',
  'arrow-up',
  'arrows-alt',
  'arrows-alt-h',
  'arrows-alt-v',
  'assistive-listening-systems',
  'asterisk',
  'at',
  'atlas',
  'atom',
  'audio-description',
  'award',
  'backspace',
  'backward',
  'balance-scale',
  'ban',
  'band-aid',
  'barcode',
  'bars',
  'baseball-ball',
  'basketball-ball',
  'bath',
  'battery-empty',
  'battery-full',
  'battery-half',
  'battery-quarter',
  'battery-three-quarters',
  'bed',
  'beer',
  'bell',
  'bell-slash',
  'bezier-curve',
  'bible',
  'bicycle',
  'binoculars',
  'birthday-cake',
  'blender',
  'blind',
  'bold',
  'bolt',
  'bomb',
  'bone',
  'bong',
  'book',
  'book-open',
  'book-reader',
  'bookmark',
  'bowling-ball',
  'box',
  'box-open',
  'boxes',
  'braille',
  'brain',
  'briefcase',
  'briefcase-medical',
  'broadcast-tower',
  'broom',
  'brush',
  'bug',
  'building',
  'bullhorn',
  'bullseye',
  'burn',
  'bus',
  'bus-alt',
  'business-time',
  'calculator',
  'calendar',
  'calendar-alt',
  'calendar-check',
  'calendar-minus',
  'calendar-plus',
  'calendar-times',
  'camera',
  'camera-retro',
  'cannabis',
  'capsules',
  'car',
  'car-alt',
  'car-battery',
  'car-crash',
  'car-side',
  'caret-down',
  'caret-left',
  'caret-right',
  'caret-square-down',
  'caret-square-left',
  'caret-square-right',
  'caret-square-up',
  'caret-up',
  'cart-arrow-down',
  'cart-plus',
  'certificate',
  'chalkboard',
  'chalkboard-teacher',
  'charging-station',
  'chart-area',
  'chart-bar',
  'chart-line',
  'chart-pie',
  'check',
  'check-circle',
  'check-double',
  'check-square',
  'chess',
  'chess-bishop',
  'chess-board',
  'chess-king',
  'chess-knight',
  'chess-pawn',
  'chess-queen',
  'chess-rook',
  'chevron-circle-down',
  'chevron-circle-left',
  'chevron-circle-right',
  'chevron-circle-up',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'child',
  'church',
  'circle',
  'circle-notch',
  'city',
  'clipboard',
  'clipboard-check',
  'clipboard-list',
  'clock',
  'clone',
  'closed-captioning',
  'cloud',
  'cloud-download-alt',
  'cloud-upload-alt',
  'cocktail',
  'code',
  'code-branch',
  'coffee',
  'cog',
  'cogs',
  'coins',
  'columns',
  'comment',
  'comment-alt',
  'comment-dollar',
  'comment-dots',
  'comment-slash',
  'comments',
  'comments-dollar',
  'compact-disc',
  'compass',
  'compress',
  'concierge-bell',
  'cookie',
  'cookie-bite',
  'copy',
  'copyright',
  'couch',
  'credit-card',
  'crop',
  'crop-alt',
  'cross',
  'crosshairs',
  'crow',
  'crown',
  'cube',
  'cubes',
  'cut',
  'database',
  'deaf',
  'desktop',
  'dharmachakra',
  'diagnoses',
  'dice',
  'dice-five',
  'dice-four',
  'dice-one',
  'dice-six',
  'dice-three',
  'dice-two',
  'digital-tachograph',
  'directions',
  'divide',
  'dizzy',
  'dna',
  'dollar-sign',
  'dolly',
  'dolly-flatbed',
  'donate',
  'door-closed',
  'door-open',
  'dot-circle',
  'dove',
  'download',
  'drafting-compass',
  'draw-polygon',
  'drum',
  'drum-steelpan',
  'dumbbell',
  'edit',
  'eject',
  'ellipsis-h',
  'ellipsis-v',
  'envelope',
  'envelope-open',
  'envelope-open-text',
  'envelope-square',
  'equals',
  'eraser',
  'euro-sign',
  'exchange-alt',
  'exclamation',
  'exclamation-circle',
  'exclamation-triangle',
  'expand',
  'expand-arrows-alt',
  'external-link-alt',
  'external-link-square-alt',
  'eye',
  'eye-dropper',
  'eye-slash',
  'fast-backward',
  'fast-forward',
  'fax',
  'feather',
  'feather-alt',
  'female',
  'fighter-jet',
  'file',
  'file-alt',
  'file-archive',
  'file-audio',
  'file-code',
  'file-contract',
  'file-download',
  'file-excel',
  'file-export',
  'file-image',
  'file-import',
  'file-invoice',
  'file-invoice-dollar',
  'file-medical',
  'file-medical-alt',
  'file-pdf',
  'file-powerpoint',
  'file-prescription',
  'file-signature',
  'file-upload',
  'file-video',
  'file-word',
  'fill',
  'fill-drip',
  'film',
  'filter',
  'fingerprint',
  'fire',
  'fire-extinguisher',
  'first-aid',
  'fish',
  'flag',
  'flag-checkered',
  'flask',
  'flushed',
  'folder',
  'folder-minus',
  'folder-open',
  'folder-plus',
  'font',
  'font-awesome-logo-full',
  'football-ball',
  'forward',
  'frog',
  'frown',
  'frown-open',
  'funnel-dollar',
  'futbol',
  'gamepad',
  'gas-pump',
  'gavel',
  'gem',
  'genderless',
  'gift',
  'glass-martini',
  'glass-martini-alt',
  'glasses',
  'globe',
  'globe-africa',
  'globe-americas',
  'globe-asia',
  'golf-ball',
  'gopuram',
  'graduation-cap',
  'greater-than',
  'greater-than-equal',
  'grimace',
  'grin',
  'grin-alt',
  'grin-beam',
  'grin-beam-sweat',
  'grin-hearts',
  'grin-squint',
  'grin-squint-tears',
  'grin-stars',
  'grin-tears',
  'grin-tongue',
  'grin-tongue-squint',
  'grin-tongue-wink',
  'grin-wink',
  'grip-horizontal',
  'grip-vertical',
  'h-square',
  'hamsa',
  'hand-holding',
  'hand-holding-heart',
  'hand-holding-usd',
  'hand-lizard',
  'hand-paper',
  'hand-peace',
  'hand-point-down',
  'hand-point-left',
  'hand-point-right',
  'hand-point-up',
  'hand-pointer',
  'hand-rock',
  'hand-scissors',
  'hand-spock',
  'hands',
  'hands-helping',
  'handshake',
  'hashtag',
  'haykal',
  'hdd',
  'heading',
  'headphones',
  'headphones-alt',
  'headset',
  'heart',
  'heartbeat',
  'helicopter',
  'highlighter',
  'history',
  'hockey-puck',
  'home',
  'hospital',
  'hospital-alt',
  'hospital-symbol',
  'hot-tub',
  'hotel',
  'hourglass',
  'hourglass-end',
  'hourglass-half',
  'hourglass-start',
  'i-cursor',
  'id-badge',
  'id-card',
  'id-card-alt',
  'image',
  'images',
  'inbox',
  'indent',
  'industry',
  'infinity',
  'info',
  'info-circle',
  'italic',
  'jedi',
  'joint',
  'journal-whills',
  'kaaba',
  'key',
  'keyboard',
  'khanda',
  'kiss',
  'kiss-beam',
  'kiss-wink-heart',
  'kiwi-bird',
  'landmark',
  'language',
  'laptop',
  'laptop-code',
  'laugh',
  'laugh-beam',
  'laugh-squint',
  'laugh-wink',
  'layer-group',
  'leaf',
  'lemon',
  'less-than',
  'less-than-equal',
  'level-down-alt',
  'level-up-alt',
  'life-ring',
  'lightbulb',
  'link',
  'lira-sign',
  'list',
  'list-alt',
  'list-ol',
  'list-ul',
  'location-arrow',
  'lock',
  'lock-open',
  'long-arrow-alt-down',
  'long-arrow-alt-left',
  'long-arrow-alt-right',
  'long-arrow-alt-up',
  'low-vision',
  'luggage-cart',
  'magic',
  'magnet',
  'mail-bulk',
  'male',
  'map',
  'map-marked',
  'map-marked-alt',
  'map-marker',
  'map-marker-alt',
  'map-pin',
  'map-signs',
  'marker',
  'mars',
  'mars-double',
  'mars-stroke',
  'mars-stroke-h',
  'mars-stroke-v',
  'medal',
  'medkit',
  'meh',
  'meh-blank',
  'meh-rolling-eyes',
  'memory',
  'menorah',
  'mercury',
  'microchip',
  'microphone',
  'microphone-alt',
  'microphone-alt-slash',
  'microphone-slash',
  'microscope',
  'minus',
  'minus-circle',
  'minus-square',
  'mobile',
  'mobile-alt',
  'money-bill',
  'money-bill-alt',
  'money-bill-wave',
  'money-bill-wave-alt',
  'money-check',
  'money-check-alt',
  'monument',
  'moon',
  'mortar-pestle',
  'mosque',
  'motorcycle',
  'mouse-pointer',
  'music',
  'neuter',
  'newspaper',
  'not-equal',
  'notes-medical',
  'object-group',
  'object-ungroup',
  'oil-can',
  'om',
  'outdent',
  'paint-brush',
  'paint-roller',
  'palette',
  'pallet',
  'paper-plane',
  'paperclip',
  'parachute-box',
  'paragraph',
  'parking',
  'passport',
  'pastafarianism',
  'paste',
  'pause',
  'pause-circle',
  'paw',
  'peace',
  'pen',
  'pen-alt',
  'pen-fancy',
  'pen-nib',
  'pen-square',
  'pencil-alt',
  'pencil-ruler',
  'people-carry',
  'percent',
  'percentage',
  'phone',
  'phone-slash',
  'phone-square',
  'phone-volume',
  'piggy-bank',
  'pills',
  'place-of-worship',
  'plane',
  'plane-arrival',
  'plane-departure',
  'play',
  'play-circle',
  'plug',
  'plus',
  'plus-circle',
  'plus-square',
  'podcast',
  'poll',
  'poll-h',
  'poo',
  'poop',
  'portrait',
  'pound-sign',
  'power-off',
  'pray',
  'praying-hands',
  'prescription',
  'prescription-bottle',
  'prescription-bottle-alt',
  'print',
  'procedures',
  'project-diagram',
  'puzzle-piece',
  'qrcode',
  'question',
  'question-circle',
  'quidditch',
  'quote-left',
  'quote-right',
  'quran',
  'random',
  'receipt',
  'recycle',
  'redo',
  'redo-alt',
  'registered',
  'reply',
  'reply-all',
  'retweet',
  'ribbon',
  'road',
  'robot',
  'rocket',
  'route',
  'rss',
  'rss-square',
  'ruble-sign',
  'ruler',
  'ruler-combined',
  'ruler-horizontal',
  'ruler-vertical',
  'rupee-sign',
  'sad-cry',
  'sad-tear',
  'save',
  'school',
  'screwdriver',
  'search',
  'search-dollar',
  'search-location',
  'search-minus',
  'search-plus',
  'seedling',
  'server',
  'shapes',
  'share',
  'share-alt',
  'share-alt-square',
  'share-square',
  'shekel-sign',
  'shield-alt',
  'ship',
  'shipping-fast',
  'shoe-prints',
  'shopping-bag',
  'shopping-basket',
  'shopping-cart',
  'shower',
  'shuttle-van',
  'sign',
  'sign-in-alt',
  'sign-language',
  'sign-out-alt',
  'signal',
  'signature',
  'sitemap',
  'skull',
  'sliders-h',
  'smile',
  'smile-beam',
  'smile-wink',
  'smoking',
  'smoking-ban',
  'snowflake',
  'socks',
  'solar-panel',
  'sort',
  'sort-alpha-down',
  'sort-alpha-up',
  'sort-amount-down',
  'sort-amount-up',
  'sort-down',
  'sort-numeric-down',
  'sort-numeric-up',
  'sort-up',
  'spa',
  'space-shuttle',
  'spinner',
  'splotch',
  'spray-can',
  'square',
  'square-full',
  'square-root-alt',
  'stamp',
  'star',
  'star-and-crescent',
  'star-half',
  'star-half-alt',
  'star-of-david',
  'star-of-life',
  'step-backward',
  'step-forward',
  'stethoscope',
  'sticky-note',
  'stop',
  'stop-circle',
  'stopwatch',
  'store',
  'store-alt',
  'stream',
  'street-view',
  'strikethrough',
  'stroopwafel',
  'subscript',
  'subway',
  'suitcase',
  'suitcase-rolling',
  'sun',
  'superscript',
  'surprise',
  'swatchbook',
  'swimmer',
  'swimming-pool',
  'synagogue',
  'sync',
  'sync-alt',
  'syringe',
  'table',
  'table-tennis',
  'tablet',
  'tablet-alt',
  'tablets',
  'tachometer-alt',
  'tag',
  'tags',
  'tape',
  'tasks',
  'taxi',
  'teeth',
  'teeth-open',
  'terminal',
  'text-height',
  'text-width',
  'th',
  'th-large',
  'th-list',
  'theater-masks',
  'thermometer',
  'thermometer-empty',
  'thermometer-full',
  'thermometer-half',
  'thermometer-quarter',
  'thermometer-three-quarters',
  'thumbs-down',
  'thumbs-up',
  'thumbtack',
  'ticket-alt',
  'times',
  'times-circle',
  'tint',
  'tint-slash',
  'tired',
  'toggle-off',
  'toggle-on',
  'toolbox',
  'tooth',
  'torah',
  'torii-gate',
  'trademark',
  'traffic-light',
  'train',
  'transgender',
  'transgender-alt',
  'trash',
  'trash-alt',
  'tree',
  'trophy',
  'truck',
  'truck-loading',
  'truck-monster',
  'truck-moving',
  'truck-pickup',
  'tshirt',
  'tty',
  'tv',
  'umbrella',
  'umbrella-beach',
  'underline',
  'undo',
  'undo-alt',
  'universal-access',
  'university',
  'unlink',
  'unlock',
  'unlock-alt',
  'upload',
  'user',
  'user-alt',
  'user-alt-slash',
  'user-astronaut',
  'user-check',
  'user-circle',
  'user-clock',
  'user-cog',
  'user-edit',
  'user-friends',
  'user-graduate',
  'user-lock',
  'user-md',
  'user-minus',
  'user-ninja',
  'user-plus',
  'user-secret',
  'user-shield',
  'user-slash',
  'user-tag',
  'user-tie',
  'user-times',
  'users',
  'users-cog',
  'utensil-spoon',
  'utensils',
  'vector-square',
  'venus',
  'venus-double',
  'venus-mars',
  'vial',
  'vials',
  'video',
  'video-slash',
  'vihara',
  'volleyball-ball',
  'volume-down',
  'volume-off',
  'volume-up',
  'walking',
  'wallet',
  'warehouse',
  'weight',
  'weight-hanging',
  'wheelchair',
  'wifi',
  'window-close',
  'window-maximize',
  'window-minimize',
  'window-restore',
  'wine-glass',
  'wine-glass-alt',
  'won-sign',
  'wrench',
  'x-ray',
  'yen-sign',
  'yin-yang',
  // '500px',
  // 'accessible-icon',
  // 'accusoft',
  // 'adn',
  // 'adversal',
  // 'affiliatetheme',
  // 'algolia',
  // 'alipay',
  // 'amazon',
  // 'amazon-pay',
  // 'amilia',
  // 'android',
  // 'angellist',
  // 'angrycreative',
  // 'angular',
  // 'app-store',
  // 'app-store-ios',
  // 'apper',
  // 'apple',
  // 'apple-pay',
  // 'asymmetrik',
  // 'audible',
  // 'autoprefixer',
  // 'avianex',
  // 'aviato',
  // 'aws',
  // 'bandcamp',
  // 'behance',
  // 'behance-square',
  // 'bimobject',
  // 'bitbucket',
  // 'bitcoin',
  // 'bity',
  // 'black-tie',
  // 'blackberry',
  // 'blogger',
  // 'blogger-b',
  // 'bluetooth',
  // 'bluetooth-b',
  // 'btc',
  // 'buromobelexperte',
  // 'buysellads',
  // 'cc-amazon-pay',
  // 'cc-amex',
  // 'cc-apple-pay',
  // 'cc-diners-club',
  // 'cc-discover',
  // 'cc-jcb',
  // 'cc-mastercard',
  // 'cc-paypal',
  // 'cc-stripe',
  // 'cc-visa',
  // 'centercode',
  // 'chrome',
  // 'cloudscale',
  // 'cloudsmith',
  // 'cloudversify',
  // 'codepen',
  // 'codiepie',
  // 'connectdevelop',
  // 'contao',
  // 'cpanel',
  // 'creative-commons',
  // 'creative-commons-by',
  // 'creative-commons-nc',
  // 'creative-commons-nc-eu',
  // 'creative-commons-nc-jp',
  // 'creative-commons-nd',
  // 'creative-commons-pd',
  // 'creative-commons-pd-alt',
  // 'creative-commons-remix',
  // 'creative-commons-sa',
  // 'creative-commons-sampling',
  // 'creative-commons-sampling-plus',
  // 'creative-commons-share',
  // 'css3',
  // 'css3-alt',
  // 'cuttlefish',
  // 'd-and-d',
  // 'dashcube',
  // 'delicious',
  // 'deploydog',
  // 'deskpro',
  // 'deviantart',
  // 'digg',
  // 'digital-ocean',
  // 'discord',
  // 'discourse',
  // 'dochub',
  // 'docker',
  // 'draft2digital',
  // 'dribbble',
  // 'dribbble-square',
  // 'dropbox',
  // 'drupal',
  // 'dyalog',
  // 'earlybirds',
  // 'ebay',
  // 'edge',
  // 'elementor',
  // 'ello',
  // 'ember',
  // 'empire',
  // 'envira',
  // 'erlang',
  // 'ethereum',
  // 'etsy',
  // 'expeditedssl',
  // 'facebook',
  // 'facebook-f',
  // 'facebook-messenger',
  // 'facebook-square',
  // 'firefox',
  // 'first-order',
  // 'first-order-alt',
  // 'firstdraft',
  // 'flickr',
  // 'flipboard',
  // 'fly',
  // 'font-awesome',
  // 'font-awesome-alt',
  // 'font-awesome-flag',
  // 'fonticons',
  // 'fonticons-fi',
  // 'fort-awesome',
  // 'fort-awesome-alt',
  // 'forumbee',
  // 'foursquare',
  // 'free-code-camp',
  // 'freebsd',
  // 'fulcrum',
  // 'galactic-republic',
  // 'galactic-senate',
  // 'get-pocket',
  // 'gg',
  // 'gg-circle',
  // 'git',
  // 'git-square',
  // 'github',
  // 'github-alt',
  // 'github-square',
  // 'gitkraken',
  // 'gitlab',
  // 'gitter',
  // 'glide',
  // 'glide-g',
  // 'gofore',
  // 'goodreads',
  // 'goodreads-g',
  // 'google',
  // 'google-drive',
  // 'google-play',
  // 'google-plus',
  // 'google-plus-g',
  // 'google-plus-square',
  // 'google-wallet',
  // 'gratipay',
  // 'grav',
  // 'gripfire',
  // 'grunt',
  // 'gulp',
  // 'hacker-news',
  // 'hacker-news-square',
  // 'hackerrank',
  // 'hips',
  // 'hire-a-helper',
  // 'hooli',
  // 'hornbill',
  // 'hotjar',
  // 'houzz',
  // 'html5',
  // 'hubspot',
  // 'imdb',
  // 'instagram',
  // 'internet-explorer',
  // 'ioxhost',
  // 'itunes',
  // 'itunes-note',
  // 'java',
  // 'jedi-order',
  // 'jenkins',
  // 'joget',
  // 'joomla',
  // 'js',
  // 'js-square',
  // 'jsfiddle',
  // 'kaggle',
  // 'keybase',
  // 'keycdn',
  // 'kickstarter',
  // 'kickstarter-k',
  // 'korvue',
  // 'laravel',
  // 'lastfm',
  // 'lastfm-square',
  // 'leanpub',
  // 'less',
  // 'line',
  // 'linkedin',
  // 'linkedin-in',
  // 'linode',
  // 'linux',
  // 'lyft',
  // 'magento',
  // 'mailchimp',
  // 'mandalorian',
  // 'markdown',
  // 'mastodon',
  // 'maxcdn',
  // 'medapps',
  // 'medium',
  // 'medium-m',
  // 'medrt',
  // 'meetup',
  // 'megaport',
  // 'microsoft',
  // 'mix',
  // 'mixcloud',
  // 'mizuni',
  // 'modx',
  // 'monero',
  // 'napster',
  // 'neos',
  // 'nimblr',
  // 'nintendo-switch',
  // 'node',
  // 'node-js',
  // 'npm',
  // 'ns8',
  // 'nutritionix',
  // 'odnoklassniki',
  // 'odnoklassniki-square',
  // 'old-republic',
  // 'opencart',
  // 'openid',
  // 'opera',
  // 'optin-monster',
  // 'osi',
  // 'page4',
  // 'pagelines',
  // 'palfed',
  // 'patreon',
  // 'paypal',
  // 'periscope',
  // 'phabricator',
  // 'phoenix-framework',
  // 'phoenix-squadron',
  // 'php',
  // 'pied-piper',
  // 'pied-piper-alt',
  // 'pied-piper-hat',
  // 'pied-piper-pp',
  // 'pinterest',
  // 'pinterest-p',
  // 'pinterest-square',
  // 'playstation',
  // 'product-hunt',
  // 'pushed',
  // 'python',
  // 'qq',
  // 'quinscape',
  // 'quora',
  // 'r-project',
  // 'ravelry',
  // 'react',
  // 'readme',
  // 'rebel',
  // 'red-river',
  // 'reddit',
  // 'reddit-alien',
  // 'reddit-square',
  // 'rendact',
  // 'renren',
  // 'replyd',
  // 'researchgate',
  // 'resolving',
  // 'rev',
  // 'rocketchat',
  // 'rockrms',
  // 'safari',
  // 'sass',
  // 'schlix',
  // 'scribd',
  // 'searchengin',
  // 'sellcast',
  // 'sellsy',
  // 'servicestack',
  // 'shirtsinbulk',
  // 'shopware',
  // 'simplybuilt',
  // 'sistrix',
  // 'sith',
  // 'skyatlas',
  // 'skype',
  // 'slack',
  // 'slack-hash',
  // 'slideshare',
  // 'snapchat',
  // 'snapchat-ghost',
  // 'snapchat-square',
  // 'soundcloud',
  // 'speakap',
  // 'spotify',
  // 'squarespace',
  // 'stack-exchange',
  // 'stack-overflow',
  // 'staylinked',
  // 'steam',
  // 'steam-square',
  // 'steam-symbol',
  // 'sticker-mule',
  // 'strava',
  // 'stripe',
  // 'stripe-s',
  // 'studiovinari',
  // 'stumbleupon',
  // 'stumbleupon-circle',
  // 'superpowers',
  // 'supple',
  // 'teamspeak',
  // 'telegram',
  // 'telegram-plane',
  // 'tencent-weibo',
  // 'the-red-yeti',
  // 'themeco',
  // 'themeisle',
  // 'trade-federation',
  // 'trello',
  // 'tripadvisor',
  // 'tumblr',
  // 'tumblr-square',
  // 'twitch',
  // 'twitter',
  // 'twitter-square',
  // 'typo3',
  // 'uber',
  // 'uikit',
  // 'uniregistry',
  // 'untappd',
  // 'usb',
  // 'ussunnah',
  // 'vaadin',
  // 'viacoin',
  // 'viadeo',
  // 'viadeo-square',
  // 'viber',
  // 'vimeo',
  // 'vimeo-square',
  // 'vimeo-v',
  // 'vine',
  // 'vk',
  // 'vnv',
  // 'vuejs',
  // 'weebly',
  // 'weibo',
  // 'weixin',
  // 'whatsapp',
  // 'whatsapp-square',
  // 'whmcs',
  // 'wikipedia-w',
  // 'windows',
  // 'wix',
  // 'wolf-pack-battalion',
  // 'wordpress',
  // 'wordpress-simple',
  // 'wpbeginner',
  // 'wpexplorer',
  // 'wpforms',
  // 'xbox',
  // 'xing',
  // 'xing-square',
  // 'y-combinator',
  // 'yahoo',
  // 'yandex',
  // 'yandex-international',
  // 'yelp',
  // 'yoast',
  // 'youtube',
  // 'youtube-square',
  // 'zhihu',
];

// export const materialIcons = [
//   '3d_rotation',
//   'ac_unit',
//   'access_alarm',
//   'access_alarms',
//   'access_time',
//   'accessibility',
//   'accessible',
//   'account_balance',
//   'account_balance_wallet',
//   'account_box',
//   'account_circle',
//   'adb',
//   'add',
//   'add_a_photo',
//   'add_alarm',
//   'add_alert',
//   'add_box',
//   'add_circle',
//   'add_circle_outline',
//   'add_location',
//   'add_shopping_cart',
//   'add_to_photos',
//   'add_to_queue',
//   'adjust',
//   'airline_seat_flat',
//   'airline_seat_flat_angled',
//   'airline_seat_individual_suite',
//   'airline_seat_legroom_extra',
//   'airline_seat_legroom_normal',
//   'airline_seat_legroom_reduced',
//   'airline_seat_recline_extra',
//   'airline_seat_recline_normal',
//   'airplanemode_active',
//   'airplanemode_inactive',
//   'airplay',
//   'airport_shuttle',
//   'alarm',
//   'alarm_add',
//   'alarm_off',
//   'alarm_on',
//   'album',
//   'all_inclusive',
//   'all_out',
//   'android',
//   'announcement',
//   'apps',
//   'archive',
//   'arrow_back',
//   'arrow_downward',
//   'arrow_drop_down',
//   'arrow_drop_down_circle',
//   'arrow_drop_up',
//   'arrow_forward',
//   'arrow_upward',
//   'art_track',
//   'aspect_ratio',
//   'assessment',
//   'assignment',
//   'assignment_ind',
//   'assignment_late',
//   'assignment_return',
//   'assignment_returned',
//   'assignment_turned_in',
//   'assistant',
//   'assistant_photo',
//   'attach_file',
//   'attach_money',
//   'attachment',
//   'audiotrack',
//   'autorenew',
//   'av_timer',
//   'backspace',
//   'backup',
//   'battery_alert',
//   'battery_charging_full',
//   'battery_full',
//   'battery_std',
//   'battery_unknown',
//   'beach_access',
//   'beenhere',
//   'block',
//   'bluetooth',
//   'bluetooth_audio',
//   'bluetooth_connected',
//   'bluetooth_disabled',
//   'bluetooth_searching',
//   'blur_circular',
//   'blur_linear',
//   'blur_off',
//   'blur_on',
//   'book',
//   'bookmark',
//   'bookmark_border',
//   'border_all',
//   'border_bottom',
//   'border_clear',
//   'border_color',
//   'border_horizontal',
//   'border_inner',
//   'border_left',
//   'border_outer',
//   'border_right',
//   'border_style',
//   'border_top',
//   'border_vertical',
//   'branding_watermark',
//   'brightness_1',
//   'brightness_2',
//   'brightness_3',
//   'brightness_4',
//   'brightness_5',
//   'brightness_6',
//   'brightness_7',
//   'brightness_auto',
//   'brightness_high',
//   'brightness_low',
//   'brightness_medium',
//   'broken_image',
//   'brush',
//   'bubble_chart',
//   'bug_report',
//   'build',
//   'burst_mode',
//   'business',
//   'business_center',
//   'cached',
//   'cake',
//   'call',
//   'call_end',
//   'call_made',
//   'call_merge',
//   'call_missed',
//   'call_missed_outgoing',
//   'call_received',
//   'call_split',
//   'call_to_action',
//   'camera',
//   'camera_alt',
//   'camera_enhance',
//   'camera_front',
//   'camera_rear',
//   'camera_roll',
//   'cancel',
//   'card_giftcard',
//   'card_membership',
//   'card_travel',
//   'casino',
//   'cast',
//   'cast_connected',
//   'center_focus_strong',
//   'center_focus_weak',
//   'change_history',
//   'chat',
//   'chat_bubble',
//   'chat_bubble_outline',
//   'check',
//   'check_box',
//   'check_box_outline_blank',
//   'check_circle',
//   'chevron_left',
//   'chevron_right',
//   'child_care',
//   'child_friendly',
//   'chrome_reader_mode',
//   'class',
//   'clear',
//   'clear_all',
//   'close',
//   'closed_caption',
//   'cloud',
//   'cloud_circle',
//   'cloud_done',
//   'cloud_download',
//   'cloud_off',
//   'cloud_queue',
//   'cloud_upload',
//   'code',
//   'collections',
//   'collections_bookmark',
//   'color_lens',
//   'colorize',
//   'comment',
//   'compare',
//   'compare_arrows',
//   'computer',
//   'confirmation_number',
//   'contact_mail',
//   'contact_phone',
//   'contacts',
//   'content_copy',
//   'content_cut',
//   'content_paste',
//   'control_point',
//   'control_point_duplicate',
//   'copyright',
//   'create',
//   'create_new_folder',
//   'credit_card',
//   'crop',
//   'crop_16_9',
//   'crop_3_2',
//   'crop_5_4',
//   'crop_7_5',
//   'crop_din',
//   'crop_free',
//   'crop_landscape',
//   'crop_original',
//   'crop_portrait',
//   'crop_rotate',
//   'crop_square',
//   'dashboard',
//   'data_usage',
//   'date_range',
//   'dehaze',
//   'delete',
//   'delete_forever',
//   'delete_sweep',
//   'description',
//   'desktop_mac',
//   'desktop_windows',
//   'details',
//   'developer_board',
//   'developer_mode',
//   'device_hub',
//   'devices',
//   'devices_other',
//   'dialer_sip',
//   'dialpad',
//   'directions',
//   'directions_bike',
//   'directions_boat',
//   'directions_bus',
//   'directions_car',
//   'directions_railway',
//   'directions_run',
//   'directions_subway',
//   'directions_transit',
//   'directions_walk',
//   'disc_full',
//   'dns',
//   'do_not_disturb',
//   'do_not_disturb_alt',
//   'do_not_disturb_off',
//   'do_not_disturb_on',
//   'dock',
//   'domain',
//   'done',
//   'done_all',
//   'donut_large',
//   'donut_small',
//   'drafts',
//   'drag_handle',
//   'drive_eta',
//   'dvr',
//   'edit',
//   'edit_location',
//   'eject',
//   'email',
//   'enhanced_encryption',
//   'equalizer',
//   'error',
//   'error_outline',
//   'euro_symbol',
//   'ev_station',
//   'event',
//   'event_available',
//   'event_busy',
//   'event_note',
//   'event_seat',
//   'exit_to_app',
//   'expand_less',
//   'expand_more',
//   'explicit',
//   'explore',
//   'exposure',
//   'exposure_neg_1',
//   'exposure_neg_2',
//   'exposure_plus_1',
//   'exposure_plus_2',
//   'exposure_zero',
//   'extension',
//   'face',
//   'fast_forward',
//   'fast_rewind',
//   'favorite',
//   'favorite_border',
//   'featured_play_list',
//   'featured_video',
//   'feedback',
//   'fiber_dvr',
//   'fiber_manual_record',
//   'fiber_new',
//   'fiber_pin',
//   'fiber_smart_record',
//   'file_download',
//   'file_upload',
//   'filter',
//   'filter_1',
//   'filter_2',
//   'filter_3',
//   'filter_4',
//   'filter_5',
//   'filter_6',
//   'filter_7',
//   'filter_8',
//   'filter_9',
//   'filter_9_plus',
//   'filter_b_and_w',
//   'filter_center_focus',
//   'filter_drama',
//   'filter_frames',
//   'filter_hdr',
//   'filter_list',
//   'filter_none',
//   'filter_tilt_shift',
//   'filter_vintage',
//   'find_in_page',
//   'find_replace',
//   'fingerprint',
//   'first_page',
//   'fitness_center',
//   'flag',
//   'flare',
//   'flash_auto',
//   'flash_off',
//   'flash_on',
//   'flight',
//   'flight_land',
//   'flight_takeoff',
//   'flip',
//   'flip_to_back',
//   'flip_to_front',
//   'folder',
//   'folder_open',
//   'folder_shared',
//   'folder_special',
//   'font_download',
//   'format_align_center',
//   'format_align_justify',
//   'format_align_left',
//   'format_align_right',
//   'format_bold',
//   'format_clear',
//   'format_color_fill',
//   'format_color_reset',
//   'format_color_text',
//   'format_indent_decrease',
//   'format_indent_increase',
//   'format_italic',
//   'format_line_spacing',
//   'format_list_bulleted',
//   'format_list_numbered',
//   'format_paint',
//   'format_quote',
//   'format_shapes',
//   'format_size',
//   'format_strikethrough',
//   'format_textdirection_l_to_r',
//   'format_textdirection_r_to_l',
//   'format_underlined',
//   'forum',
//   'forward',
//   'forward_10',
//   'forward_30',
//   'forward_5',
//   'free_breakfast',
//   'fullscreen',
//   'fullscreen_exit',
//   'functions',
//   'g_translate',
//   'gamepad',
//   'games',
//   'gavel',
//   'gesture',
//   'get_app',
//   'gif',
//   'golf_course',
//   'gps_fixed',
//   'gps_not_fixed',
//   'gps_off',
//   'grade',
//   'gradient',
//   'grain',
//   'graphic_eq',
//   'grid_off',
//   'grid_on',
//   'group',
//   'group_add',
//   'group_work',
//   'hd',
//   'hdr_off',
//   'hdr_on',
//   'hdr_strong',
//   'hdr_weak',
//   'headset',
//   'headset_mic',
//   'healing',
//   'hearing',
//   'help',
//   'help_outline',
//   'high_quality',
//   'highlight',
//   'highlight_off',
//   'history',
//   'home',
//   'hot_tub',
//   'hotel',
//   'hourglass_empty',
//   'hourglass_full',
//   'http',
//   'https',
//   'image',
//   'image_aspect_ratio',
//   'import_contacts',
//   'import_export',
//   'important_devices',
//   'inbox',
//   'indeterminate_check_box',
//   'info',
//   'info_outline',
//   'input',
//   'insert_chart',
//   'insert_comment',
//   'insert_drive_file',
//   'insert_emoticon',
//   'insert_invitation',
//   'insert_link',
//   'insert_photo',
//   'invert_colors',
//   'invert_colors_off',
//   'iso',
//   'keyboard',
//   'keyboard_arrow_down',
//   'keyboard_arrow_left',
//   'keyboard_arrow_right',
//   'keyboard_arrow_up',
//   'keyboard_backspace',
//   'keyboard_capslock',
//   'keyboard_hide',
//   'keyboard_return',
//   'keyboard_tab',
//   'keyboard_voice',
//   'kitchen',
//   'label',
//   'label_outline',
//   'landscape',
//   'language',
//   'laptop',
//   'laptop_chromebook',
//   'laptop_mac',
//   'laptop_windows',
//   'last_page',
//   'launch',
//   'layers',
//   'layers_clear',
//   'leak_add',
//   'leak_remove',
//   'lens',
//   'library_add',
//   'library_books',
//   'library_music',
//   'lightbulb_outline',
//   'line_style',
//   'line_weight',
//   'linear_scale',
//   'link',
//   'linked_camera',
//   'list',
//   'live_help',
//   'live_tv',
//   'local_activity',
//   'local_airport',
//   'local_atm',
//   'local_bar',
//   'local_cafe',
//   'local_car_wash',
//   'local_convenience_store',
//   'local_dining',
//   'local_drink',
//   'local_florist',
//   'local_gas_station',
//   'local_grocery_store',
//   'local_hospital',
//   'local_hotel',
//   'local_laundry_service',
//   'local_library',
//   'local_mall',
//   'local_movies',
//   'local_offer',
//   'local_parking',
//   'local_pharmacy',
//   'local_phone',
//   'local_pizza',
//   'local_play',
//   'local_post_office',
//   'local_printshop',
//   'local_see',
//   'local_shipping',
//   'local_taxi',
//   'location_city',
//   'location_disabled',
//   'location_off',
//   'location_on',
//   'location_searching',
//   'lock',
//   'lock_open',
//   'lock_outline',
//   'looks',
//   'looks_3',
//   'looks_4',
//   'looks_5',
//   'looks_6',
//   'looks_one',
//   'looks_two',
//   'loop',
//   'loupe',
//   'low_priority',
//   'loyalty',
//   'mail',
//   'mail_outline',
//   'map',
//   'markunread',
//   'markunread_mailbox',
//   'memory',
//   'menu',
//   'merge_type',
//   'message',
//   'mic',
//   'mic_none',
//   'mic_off',
//   'mms',
//   'mode_comment',
//   'mode_edit',
//   'monetization_on',
//   'money_off',
//   'monochrome_photos',
//   'mood',
//   'mood_bad',
//   'more',
//   'more_horiz',
//   'more_vert',
//   'motorcycle',
//   'mouse',
//   'move_to_inbox',
//   'movie',
//   'movie_creation',
//   'movie_filter',
//   'multiline_chart',
//   'music_note',
//   'music_video',
//   'my_location',
//   'nature',
//   'nature_people',
//   'navigate_before',
//   'navigate_next',
//   'navigation',
//   'near_me',
//   'network_cell',
//   'network_check',
//   'network_locked',
//   'network_wifi',
//   'new_releases',
//   'next_week',
//   'nfc',
//   'no_encryption',
//   'no_sim',
//   'not_interested',
//   'note',
//   'note_add',
//   'notifications',
//   'notifications_active',
//   'notifications_none',
//   'notifications_off',
//   'notifications_paused',
//   'offline_pin',
//   'ondemand_video',
//   'opacity',
//   'open_in_browser',
//   'open_in_new',
//   'open_with',
//   'pages',
//   'pageview',
//   'palette',
//   'pan_tool',
//   'panorama',
//   'panorama_fish_eye',
//   'panorama_horizontal',
//   'panorama_vertical',
//   'panorama_wide_angle',
//   'party_mode',
//   'pause',
//   'pause_circle_filled',
//   'pause_circle_outline',
//   'payment',
//   'people',
//   'people_outline',
//   'perm_camera_mic',
//   'perm_contact_calendar',
//   'perm_data_setting',
//   'perm_device_information',
//   'perm_identity',
//   'perm_media',
//   'perm_phone_msg',
//   'perm_scan_wifi',
//   'person',
//   'person_add',
//   'person_outline',
//   'person_pin',
//   'person_pin_circle',
//   'personal_video',
//   'pets',
//   'phone',
//   'phone_android',
//   'phone_bluetooth_speaker',
//   'phone_forwarded',
//   'phone_in_talk',
//   'phone_iphone',
//   'phone_locked',
//   'phone_missed',
//   'phone_paused',
//   'phonelink',
//   'phonelink_erase',
//   'phonelink_lock',
//   'phonelink_off',
//   'phonelink_ring',
//   'phonelink_setup',
//   'photo',
//   'photo_album',
//   'photo_camera',
//   'photo_filter',
//   'photo_library',
//   'photo_size_select_actual',
//   'photo_size_select_large',
//   'photo_size_select_small',
//   'picture_as_pdf',
//   'picture_in_picture',
//   'picture_in_picture_alt',
//   'pie_chart',
//   'pie_chart_outlined',
//   'pin_drop',
//   'place',
//   'play_arrow',
//   'play_circle_filled',
//   'play_circle_outline',
//   'play_for_work',
//   'playlist_add',
//   'playlist_add_check',
//   'playlist_play',
//   'plus_one',
//   'poll',
//   'polymer',
//   'pool',
//   'portable_wifi_off',
//   'portrait',
//   'power',
//   'power_input',
//   'power_settings_new',
//   'pregnant_woman',
//   'present_to_all',
//   'print',
//   'priority_high',
//   'public',
//   'publish',
//   'query_builder',
//   'question_answer',
//   'queue',
//   'queue_music',
//   'queue_play_next',
//   'radio',
//   'radio_button_checked',
//   'radio_button_unchecked',
//   'rate_review',
//   'receipt',
//   'recent_actors',
//   'record_voice_over',
//   'redeem',
//   'redo',
//   'refresh',
//   'remove',
//   'remove_circle',
//   'remove_circle_outline',
//   'remove_from_queue',
//   'remove_red_eye',
//   'remove_shopping_cart',
//   'reorder',
//   'repeat',
//   'repeat_one',
//   'replay',
//   'replay_10',
//   'replay_30',
//   'replay_5',
//   'reply',
//   'reply_all',
//   'report',
//   'report_problem',
//   'restaurant',
//   'restaurant_menu',
//   'restore',
//   'restore_page',
//   'ring_volume',
//   'room',
//   'room_service',
//   'rotate_90_degrees_ccw',
//   'rotate_left',
//   'rotate_right',
//   'rounded_corner',
//   'router',
//   'rowing',
//   'rss_feed',
//   'rv_hookup',
//   'satellite',
//   'save',
//   'scanner',
//   'schedule',
//   'school',
//   'screen_lock_landscape',
//   'screen_lock_portrait',
//   'screen_lock_rotation',
//   'screen_rotation',
//   'screen_share',
//   'sd_card',
//   'sd_storage',
//   'search',
//   'security',
//   'select_all',
//   'send',
//   'sentiment_dissatisfied',
//   'sentiment_neutral',
//   'sentiment_satisfied',
//   'sentiment_very_dissatisfied',
//   'sentiment_very_satisfied',
//   'settings',
//   'settings_applications',
//   'settings_backup_restore',
//   'settings_bluetooth',
//   'settings_brightness',
//   'settings_cell',
//   'settings_ethernet',
//   'settings_input_antenna',
//   'settings_input_component',
//   'settings_input_composite',
//   'settings_input_hdmi',
//   'settings_input_svideo',
//   'settings_overscan',
//   'settings_phone',
//   'settings_power',
//   'settings_remote',
//   'settings_system_daydream',
//   'settings_voice',
//   'share',
//   'shop',
//   'shop_two',
//   'shopping_basket',
//   'shopping_cart',
//   'short_text',
//   'show_chart',
//   'shuffle',
//   'signal_cellular_4_bar',
//   'signal_cellular_connected_no_internet_4_bar',
//   'signal_cellular_no_sim',
//   'signal_cellular_null',
//   'signal_cellular_off',
//   'signal_wifi_4_bar',
//   'signal_wifi_4_bar_lock',
//   'signal_wifi_off',
//   'sim_card',
//   'sim_card_alert',
//   'skip_next',
//   'skip_previous',
//   'slideshow',
//   'slow_motion_video',
//   'smartphone',
//   'smoke_free',
//   'smoking_rooms',
//   'sms',
//   'sms_failed',
//   'snooze',
//   'sort',
//   'sort_by_alpha',
//   'spa',
//   'space_bar',
//   'speaker',
//   'speaker_group',
//   'speaker_notes_off',
//   'speaker_phone',
//   'spellcheck',
//   'star',
//   'star_border',
//   'star_half',
//   'stars',
//   'stay_current_landscape',
//   'stay_current_portrait',
//   'stay_primary_landscape',
//   'stay_primary_portrait',
//   'stop',
//   'stop_screen_share',
//   'storage',
//   'store',
//   'store_mall_directory',
//   'straighten',
//   'streetview',
//   'strikethrough_s',
//   'style',
//   'subdirectory_arrow_left',
//   'subdirectory_arrow_right',
//   'subject',
//   'subscriptions',
//   'subtitles',
//   'subway',
//   'supervisor_account',
//   'surround_sound',
//   'swap_calls',
//   'swap_horiz',
//   'swap_vert',
//   'swap_vertical_circle',
//   'switch_camera',
//   'switch_video',
//   'sync',
//   'sync_disabled',
//   'sync_problem',
//   'system_update',
//   'system_update_alt',
//   'tab',
//   'tab_unselected',
//   'tablet',
//   'tablet_android',
//   'tablet_mac',
//   'tag_faces',
//   'tap_and_play',
//   'terrain',
//   'text_fields',
//   'text_format',
//   'textsms',
//   'texture',
//   'theaters',
//   'thumb_down',
//   'thumb_up',
//   'thumbs_up_down',
//   'time_to_leave',
//   'timelapse',
//   'timeline',
//   'timer',
//   'timer_10',
//   'timer_3',
//   'timer_off',
//   'title',
//   'toc',
//   'today',
//   'toll',
//   'tonality',
//   'touch_app',
//   'toys',
//   'track_changes',
//   'traffic',
//   'train',
//   'tram',
//   'transfer_within_a_station',
//   'transform',
//   'translate',
//   'trending_down',
//   'trending_flat',
//   'trending_up',
//   'tune',
//   'turned_in',
//   'turned_in_not',
//   'tv',
//   'unarchive',
//   'undo',
//   'unfold_less',
//   'unfold_more',
//   'update',
//   'usb',
//   'verified_user',
//   'vertical_align_bottom',
//   'vertical_align_center',
//   'vertical_align_top',
//   'vibration',
//   'video_call',
//   'video_label',
//   'video_library',
//   'videocam',
//   'videocam_off',
//   'videogame_asset',
//   'view_agenda',
//   'view_array',
//   'view_carousel',
//   'view_column',
//   'view_comfy',
//   'view_compact',
//   'view_day',
//   'view_headline',
//   'view_list',
//   'view_module',
//   'view_quilt',
//   'view_stream',
//   'view_week',
//   'vignette',
//   'visibility',
//   'visibility_off',
//   'voice_chat',
//   'voicemail',
//   'volume_down',
//   'volume_mute',
//   'volume_off',
//   'volume_up',
//   'vpn_key',
//   'vpn_lock',
//   'wallpaper',
//   'warning',
//   'watch',
//   'watch_later',
//   'wb_auto',
//   'wb_cloudy',
//   'wb_incandescent',
//   'wb_iridescent',
//   'wb_sunny',
//   'wc',
//   'web',
//   'web_asset',
//   'weekend',
//   'whatshot',
//   'widgets',
//   'wifi',
//   'wifi_lock',
//   'wifi_tethering',
//   'work',
//   'wrap_text',
//   'youtube_searched_for',
//   'zoom_in',
//   'zoom_out',
//   'zoom_out_map',
// ];
